/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#b4c5ff',
        'surface-dim': '#d8dadc',
        'on-tertiary-container': '#eef0ff',
        'surface-variant': '#e0e3e5',
        'on-background': '#191c1e',
        'on-tertiary-fixed-variant': '#3f465c',
        'surface-container-high': '#e6e8ea',
        'secondary-container': '#d0e1fb',
        'outline-variant': '#c3c6d7',
        background: '#f7f9fb',
        'on-secondary': '#ffffff',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#eff1f3',
        'inverse-surface': '#2d3133',
        error: '#ba1a1a',
        'secondary-fixed-dim': '#b7c8e1',
        'surface-container-low': '#f2f4f6',
        'on-error-container': '#93000a',
        'surface-container': '#eceef0',
        'on-error': '#ffffff',
        'on-surface': '#191c1e',
        primary: '#004ac6',
        'on-tertiary': '#ffffff',
        'on-primary-container': '#eeefff',
        'surface-container-lowest': '#ffffff',
        secondary: '#505f76',
        'tertiary-fixed': '#dae2fd',
        tertiary: '#4d556b',
        'on-surface-variant': '#434655',
        'tertiary-container': '#656d84',
        'error-container': '#ffdad6',
        'on-secondary-container': '#54647a',
        'surface-container-highest': '#e0e3e5',
        'on-primary-fixed': '#00174b',
        outline: '#737686',
        'primary-container': '#2563eb',
        'primary-fixed': '#dbe1ff',
        'on-secondary-fixed-variant': '#38485d',
        'surface-bright': '#f7f9fb',
        'inverse-primary': '#b4c5ff',
        'secondary-fixed': '#d3e4fe',
        'on-secondary-fixed': '#0b1c30',
        'surface-tint': '#0053db',
        'on-tertiary-fixed': '#131b2e',
        surface: '#f7f9fb',
        'on-primary-fixed-variant': '#003ea8',
        'tertiary-fixed-dim': '#bec6e0',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'stack-md': '16px',
        'container-max-width': '768px',
        'margin-focus': '48px',
        'stack-lg': '32px',
        'stack-sm': '8px',
        gutter: '24px',
      },
      fontFamily: {
        'headline-md': ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'display-active': ['Manrope', 'sans-serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'label-sm': ['Manrope', 'sans-serif'],
        'display-inactive': ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-active': [
          '32px',
          { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'display-inactive': [
          '32px',
          { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '500' },
        ],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
